baseURL = "http://blog.calebjay.com/"
languageCode = "en-us"
title = "Caleb's Blog"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""
timeout = 6000000
[params.author]
name = "Caleb Rogers"
email = "caleb@calebjay.com"


preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
# pygmentsCodefences = true

[params.info]
description = "A blog by Caleb on programming, writing, traveling, and philosophy."
title404 = "File Not Found."

[taxonomies]
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

defaultContentLanguage = 'en'
[languages]
  [languages.zh]
    languageName = 'Mandarin, Traditional'
    weight = 2
  [languages.en]
    languageName = 'English'
    weight = 1
